export const KEYBOARD_ACTION_TYPES = {
  REGISTER_ITEM: 'REGISTER_ITEM',
  UNREGISTER_ITEM: 'UNREGISTER_ITEM',
  PRESS_KEY: 'PRESS_KEY',
  CHANGE_VALUE: 'CHANGE_VALUE',
  FOCUS: 'FOCUS',
  BLUR: 'BLUR',
  REGISTER_KEYBOARD: 'REGISTER_KEYBOARD',
  UNREGISTER_KEYBOARD: 'UNREGISTER_KEYBOARD',
};
